### ISSUE TITLE
Peer review2

### ISSUE THREAD

**Issue by hanrastic** [ni-eminen/database-app#1]
# Peer review

* Maybe some note on how to create an account/signup or something, now signing up happens from login.

* Trying to do a quiz before signup and login causes an URL error. Some feature to avoid this could be nice.

* Some code refactoring could be nice as well. I.e move DB functions to separate module.

* Code itself is clean, but a bit crowded since everything is in app.py 

* UI is very clean and easy on the eye. Good job on that. :)

**Comment by ni-eminen** [comment]
Appropriate comments. Fixed.
